import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children, params: { locale } }) {
	console.log(locale, "locale");

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
export async function generateStaticParams() {
	// return [{ lang: "en-US" }, { lang: "en" }];
	return { locale: "en" };
}
