import { Inter } from "next/font/google";
import "./globals.css";
import { getDictionary } from "./dictionaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default async function RootLayout({ children, params: { locale } }) {
	// console.log(locale, "locale");
	const t = await getDictionary(locale);

	console.log(t);

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
